### ISSUE TITLE
Make link colors more readable

### ISSUE THREAD

**Issue by tzekid** [phseiff/phseiff.github.io#15]
There are better contrast colors for your background. E.g.

This is bad: 
![Screenshot_20200924_194803](https://user-images.githubusercontent.com/6037154/94181057-39ba7e80-fe9f-11ea-9319-10be1458458f.png)

with turquoise `rgb(175,238,238)` for `a` elements ...

![Screenshot_20200924_195015](https://user-images.githubusercontent.com/6037154/94181121-4a6af480-fe9f-11ea-968d-38cd6b517bf5.png)

much better.

**Comment by phseiff** [comment]
That's an easy thing to do, I will do that. Thanks for your issue!

**Comment by phseiff** [comment]
This appears to be more difficult than I thought since I have [darkreader](https://github.com/darkreader/darkreader#using-for-a-website) embedded in my website, which inverts the colors with js.
EDIT: Okay, it actually works. I forgot that I had the `.css` cached in the browser.

The color is more readable now, though I might change it again in the future since I feel it might be a little *too* light now.
